AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: MyPipeline
      RoleArn: arn:aws:iam::645291897239:role/service-role/AWSCodePipelineServiceRole-eu-north-1-glue-etl-pipeline
      ArtifactStore:
        Type: S3
        Location: aws-dataengineer
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: samaralir
                Repo: glue_etl_job
                Branch: main
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                StackName: glue-etl1-deploy
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: SourceOutput::project2/template.yml
